### ISSUE TITLE
`QueryState` uses the same pattern as `HistoryOptions`

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1327]
* `HistoryOptions` is a Java interface backed by a Clojure record (in `crux.history-options`)
* Functions in the Clojure `PCruxNode` protocol accept a map that they then convert into a `HistoryOptions` record when they pass it to the Java API
* May be a slight adaptation needed for QueryState - HistoryOptions is only ever passed to Crux, QueryState is only ever returned from the API.

**Comment by jarohen** [comment]
Places to look:
* Probably best to get familiar with Clojure protocols, records, `extend-protocol`
* `ICruxAPI` - main Java interface
* `api.clj`:
  * Contains the `PCruxNode` protocol, the Clojure entry point
  * Contains an `extend-protocol` instance which means that implementations of `ICruxAPI` satisfy the `PCruxNode` protocol.
* `node.clj` - contains a record that implements `ICruxAPI`

So, from Java, Crux calls are fairly direct - the node object implements `ICruxAPI` directly. Clojure users call functions on the `PCruxNode` protocol - these first hit the wrappers in the `extend-protocol`, which call through to underlying `ICruxAPI` record. This gives us the opportunity to adapt both parameters and return values between Clojure and Java.

We've settled on this way so that both Clojure and Java users can use the same 'node' object. The converse isn't possible - you can't add an implementation of an interface to an existing class. (We could, arguably, implement both the interface and the protocol on the same node record, I don't recall why we don't)

**Comment by AlistairONeill** [comment]
I have replaced the class `QueryState` with the interface `IQueryState` and how it is generated in `query_state.clj` to bring it more in line with `HistoryOptions` [See](https://github.com/AlistairONeill/crux/compare/master...AlistairONeill:aon-query-state)

I'm a little confused about how to make the change to allow users to use the `QueryState` clojure record without breaking a bunch of things when they expect a map rather than a record.

As it stands, for example, `active-queries` effectively maps 
`(vals (:in-progress @!running-queries))` with `qs/->QueryState` and then immediately back with `qs/<-QueryState`

Removing the map back would make `active-queries` return a list of `QueryState` but I am not sure how to go about discovering the knock-on consequences of this

**Comment by AlistairONeill** [comment]
Discussed with Dan and am happy it is fine to pass through the records rather than converting back.

Possible sticking point is the IQueryState.QueryStatus enum as ideally don't want to have other places in Clojure needing to refer to the Java cases.

Will need a few tweaks in various packages which I am looking at now

**Comment by jarohen** [comment]
Enums - without being fully in context, we can convert these back and forth to keywords at the Clojure/Java boundary if this makes things easier - see `HistoryOptions$SortOrder`

**Comment by AlistairONeill** [comment]
Awesome, I have done that and now things are much happier! Down to only three errors in tests
