### ISSUE TITLE
Java users can submit a strongly-typed transaction

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1328]
Currently, to submit a transaction, Java users need to pass a Clojure data structure of transaction operations (tx-ops). We'd prefer them to use a stronger-typed API, so that their IDEs can help them out.

To consider:
* Before heading into a full implementation, let's discuss a proposal for what this could look like from a user's point-of-view.
* There are various places through `ICruxAPI` and `ICruxDatasource` that either accept or return transactions - `submitTx` and `openTxLog` being the two that spring to mind, but I dare say there's more.
* Let's make sure that whatever we implement here only needs a thin Kotlin layer to become an idiomatic Kotlin DSL.
* The concept of a 'document' is pretty pervasive through these APIs - this is arguably the most important thing to get right. At the moment it's just a map, but there's probably a few different routes we could take, ranging from more weakly to more strongly typed, from simple to complex. Let's list these out as part of the proposal, discuss pros/cons, etc.

Out of scope:
* Queries, and anything query related. Coming soon :)

**Comment by AlistairONeill** [comment]
A transaction is a PersistentVector of tx-ops
Each tx-op is a PersistentVector which begins with a `:crux.tx/...` keyword which defines which operation it is.

This means that if we had four classes, one to represent each tx-op type, it is easy to go back and forth from the PersistentVector representation to the Java class representation as we can have a factory that lives on our abstract class that switches based on the first value in the vector.

In terms of what lives on each of the tx-ops, I don't think we can abstract too much to a base tx-ops class as:
PUT needs {Document}, validTime? and endValidTime? (with endValidTime not allowed to be non-null if validTime is null)
MATCH needs {Document?}, validTime?
DELETE needs {DocumentId?}, validTime? and endValidTime? (with the above constraint)
EVICT needs {DocumentId?}

I would propose making the classes to represent the actual tx-ops immutable and facilitate their creation with mutable Builders

By interacting with the builders using the `Consumer<FooBuilder>` pattern, we can have a visually nice way of creating our tx-ops.

I'd suggest modifying the pattern used for NodeConfiguration slightly. Rather than having the acceptance of the Consumer happen in the method that is passed the consumer, create a static method on the NodeConfigurator which takes a consumer and returns a new instance which has been accepted. 
This has 2 main benefits: 
 - When we are reusing a Builder class, we don't have to duplicate the f.accepts() pattern in each place it is used
 - A static build method allows users to create their Configuration/TxOp elsewhere and then pass in the built version rather than needing to build in the place they are making use of it
 
 In terms of Kotlin DSL, our main problem is that the syntax when passing in `Foo.()->Unit` and `(Foo)->Unit` is identical.
 This, coupled with the fact that `(Foo)->Unit` === `Consumer<Foo>` means that we might run into issues if we want to use the same method names.

**Comment by AlistairONeill** [comment]
A "Document" is an` IPersistentMap` from keywords to Clojure data structures
We have the additional constraint that there must exist :crux.db/id to an ID of one of the following types:
- Keyword 
- String
- Integers/Longs
- UUID
- URI
- URL
- Maps

As far as I am aware, there isn't a convenient way of stating a value must be one of a list of specific types unless they share a common ancestor not shared by others. So I think the best approach for enforcing the type of DocumentId is the one from api.alpha where we have a wrapper class with public constructors of the required types that all set a variable of type object.

I think the best way to implement documents is to have an interface with methods along the lines of:
DocumentId getDocumentId()
Map<Keyword, *> getDocumentContents()

Then we can have a method with default implementation to combine the above to produce one IPersistentMap.

This requires that we meet all of the above conditions for a document except for the one that requires values to be Clojure data structures. Trying to enforce this at compile time feels like a trickier task.

We would also need a basic implementation of the interface to use when recreating Tx-Ops from openTxLog

This also gives us the ability to hide away the explicit existence of `:crux.db/id` and the requirement to know it is special. I still think we should throw a runtime exception if getDocumentContents() includes that key as we don't want a user to accidentally overwrite data when the document map is generated.

**Comment by jarohen** [comment]
Sounds reasonable :) 

> A transaction is a PersistentVector of tx-ops
> Each tx-op is a PersistentVector which begins with a `:crux.tx/...` keyword which defines which operation it is.
> 
> This means that if we had four classes, one to represent each tx-op type, it is easy to go back and forth from the PersistentVector representation to the Java class representation as we can have a factory that lives on our abstract class that switches based on the first value in the vector.
> 
> In terms of what lives on each of the tx-ops, I don't think we can abstract too much to a base tx-ops class as:
> PUT needs {Document}, validTime? and endValidTime? (with endValidTime not allowed to be non-null if validTime is null)
> MATCH needs {Document?}, validTime?
> DELETE needs {DocumentId?}, validTime? and endValidTime? (with the above constraint)
> EVICT needs {DocumentId?}

Couple of slight alterations here:
* With `put`, I'd model the `valid-time` and `start-valid-time`/`end-valid-time` cases separately in Java, even if they look similar in Clojure
* Match needs DocumentId and optionally Document - you can specify that a document _doesn't_ yet exist by specifying a nil document.
* Delete, Evict require DocumentId

> I'd suggest modifying the pattern used for NodeConfiguration slightly. Rather than having the acceptance of the Consumer happen in the method that is passed the consumer, create a static method on the NodeConfigurator which takes a consumer and returns a new instance which has been accepted.
> This has 2 main benefits:
>
>  * When we are reusing a Builder class, we don't have to duplicate the f.accepts() pattern in each place it is used
>  * A static build method allows users to create their Configuration/TxOp elsewhere and then pass in the built version rather than needing to build in the place they are making use of it 
> 
> In terms of Kotlin DSL, our main problem is that the syntax when passing in `Foo.()->Unit` and `(Foo)->Unit` is identical.
> This, coupled with the fact that `(Foo)->Unit` === `Consumer<Foo>` means that we might run into issues if we want to use the same method names.

I'm sure this is a good idea but I can't quite picture what it looks like - maybe a usage example/small branch would help?

**Comment by jarohen** [comment]
> As far as I am aware, there isn't a convenient way of stating a value must be one of a list of specific types unless they share a common ancestor not shared by others. So I think the best approach for enforcing the type of DocumentId is the one from api.alpha where we have a wrapper class with public constructors of the required types that all set a variable of type object.

Yep, we couldn't think of a better way either!
 
> I think the best way to implement documents is to have an interface with methods along the lines of:
> DocumentId getDocumentId()
> Map<Keyword, *> getDocumentContents()
> 
> Then we can have a method with default implementation to combine the above to produce one IPersistentMap.

Yep. Let's try not to expose the concept of `Keyword` to Java users if possible (will add to the issue description) - maybe we can use a similar pattern to the NodeConfigurator?

> This requires that we meet all of the above conditions for a document except for the one that requires values to be Clojure data structures. Trying to enforce this at compile time feels like a trickier task.

Happy to cover this with documentation - we're discussing restricting these to JSON-like types in the near future
 
> We would also need a basic implementation of the interface to use when recreating Tx-Ops from openTxLog

Yep - what'd be most helpful to Java users here?

> This also gives us the ability to hide away the explicit existence of `:crux.db/id` and the requirement to know it is special. I still think we should throw a runtime exception if getDocumentContents() includes that key as we don't want a user to accidentally overwrite data when the document map is generated.

Agreed.

When you're ready, could we run over what this would look like from a user's PoV? If you could set up skeletons of all of the involved classes, maybe, and then we can pair?

**Comment by AlistairONeill** [comment]
>With put, I'd model the valid-time and start-valid-time/end-valid-time cases separately in Java, even if they look similar in Clojure

Is there a reason to split these out beyond emphasising that they are very different kettles of fish?

> I'm sure this is a good idea but I can't quite picture what it looks like - maybe a usage example/small branch would help?

a5ae8f5 for an example. It adds slightly more code to our side, but splitting out the builder from the Configuration allows more flexibility for a user and reuse of the Configuration (or TxOp etc)

>Yep. Let's try not to expose the concept of Keyword to Java users if possible (will add to the issue description) - maybe we can use a similar pattern to the NodeConfigurator?

For anything that *has* to be a keyword (e.g. keys in a document), we can let it be a String in Java land and then intern it before passing over to Clojure.
The issue I forsee is where things can be Keywords or Strings (e.g. values in a document). We can't go converting people's Strings willy nilly. Although I imagine that most Java users won't have/want keywords as values

> Yep - what'd be most helpful to Java users here?

In bb4e146, I just made a simple decoder from the PersistentArrayMap we will be getting back.
`Object get(String key)` and then the `CruxId getDocumentId()` should cover basic uses for now.

>When you're ready, could we run over what this would look like from a user's PoV? If you could set up skeletons of all of the involved classes, maybe, and then we can pair?

I'll work on getting something together this evening that isn't embarrassing to work on. I'm still getting back into the Java muscle memory and not putting `name: Type`

**Comment by AlistairONeill** [comment]
I've got the transactions working and tests all passing.

With lein-junit, running `lein test` on crux-core also runs the JUnit tests.
In terms of testing, I'm struggling to get the tests that call into the clojure code to run in the IDE (i.e. anything that needs an actual node). This means I don't have coverage metrics.

As discussed, rather than wrapping the `crux.db/id` in an object, I have now changed it to accept any object.
For safety, I have added `CruxIdException.assertValidType(Object)` which throws a Runtime exception when the id isn't a valid type. For Ids of type Map, there isn't currently any validation on the types within that map.

One thing I am not certain about is the entry point. If it were just Java world, I'd add default methods to ICruxIngestAPI to submitTx using a Transaction object that pass through to the List<List<*>> method, but I'm a little concerned about the Clojure implications of adding to the API interface. 

Currently need to add tests to verify that the TxLog is decomposed to Transaction objects correctly.

**Comment by AlistairONeill** [comment]
Having a bit of trouble with tests for creating Transaction objects from the TxLog results.

Match/Delete/Evict operations have the Ids hashed which makes comparison difficult.

Is there a map accessible somewhere to get from id hash back to the actual id?

Java doesn't seem to like importing crux.codec.Id which makes things fiddlier
