### ISSUE TITLE
high CPU usage when starting JDBC sqlite node

### ISSUE THREAD

**Issue by mallt** [xtdb/xtdb#1502]
When starting a sqlite JDBC node with the following configuration, the CPU of a Linux VPS with 2 CPU cores starts running at 100% for approximately 10 minutes:
``` clojure
{:crux.jdbc/connection-pool {:dialect {:crux/module 'crux.jdbc.sqlite/->dialect}
	                     :db-spec {:dbname "test-db"}}
 :crux/tx-log {:crux/module 'crux.jdbc/->tx-log
	       :connection-pool :crux.jdbc/connection-pool}
 :crux/document-store {:crux/module 'crux.jdbc/->document-store
	               :connection-pool :crux.jdbc/connection-pool}}
```

The sqlite db has a size of 31M. I'm using version `21.04-1.16.0-beta` of both `crux-core` and `crux-jdbc`:
``` clojure
[juxt/crux-core "21.04-1.16.0-beta"]
[juxt/crux-jdbc "21.04-1.16.0-beta"]
```

I was wondering if it is possible to change a specific configuration parameter in order to lower the initial CPU usage?

Thanks a lot!

**Comment by refset** [comment]
Hi @mallt thanks for the report! It's likely that you are experiencing the effects of https://github.com/juxt/crux/issues/1463 which we are actively working (e.g. fixing Postgres today here https://github.com/juxt/crux/commit/d88c6f5a2f4a9d7b5ca95f44459489890bb06b68, but the SQLite fix is still to come)

However, if you configure your RocksDB or LMDB index-store (as per e.g. https://opencrux.com/reference/21.04-1.16.0/rocksdb.html) then you can avoid some of the immediate inconvenience, since the indexes will be persisted between restarts instead of the current behaviour which is replaying the entire log each time (and because of that bug replaying is very expensive). With up-to-date indexes the startup time should be pretty quick.

I hope that helps - please keep us posted :)

**Comment by mallt** [comment]
Hi @refset I can indeed confirm that adding RocksDB as index-store fixes the issue.

Thanks a lot for the quick reply!

**Comment by refset** [comment]
Great, I'm glad to hear that! Your feedback here is appreciated, and we'll try to get #1463 sorted asap.
