### ISSUE TITLE
Allowing tx-times from external systems to be preserved in Crux, e.g. for import

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1517]
From @seeday on Slack, requesting the ability to explicitly specify tx-times when submitting transactions.

I doubt we'd be able to allow _any_ tx-time - if we were to receive out-of-order tx-times I'd guess this would break Crux's tx ingestion - but we might be able to allow tx-times to be explicitly specified so long as no later tx-time has yet been submitted.

**Comment by luposlip** [comment]
Would be a great addition, and the transactions could be sorted, oldest first, for ingestion.

**Comment by skat-kurt** [comment]
This is crucial functionality when importing existing bitermporal data into crux, data where the transaction times from the previous system are part of the business domain. I agree that a constraint could be that when explicitly stating the tx-time, that it must be 'later' than the last registered transaction's tx-time.

That way one could load for example from tx-time 1980-01-01 to today. You could consider to stop allowing for explicit tx-time once a transaction is committed that did not specify one, as this should mean that all data is migrated and new production data is entering the system.

**Comment by refset** [comment]
This has also just come up on Zulip in regards sync/migration between prod<->dev environments https://juxt-oss.zulipchat.com/#narrow/stream/194466-crux/topic/Migrations.20or.20other.20--.20How.20to.20keep.20Crux.20data.20in.20sync.3F

**Comment by refset** [comment]
This has come up in conversation once again in relation to making (userspace) schema changes to how a domain graph is represented as XT entities, where (possibly) the easiest thing to do is to rebuild the database (tx-log / doc-store) entirely and re-ingest everything again from upstream data sources. The use-case demands that original ingest transaction times (where applicable) are preserved so that the possibility for accurate business audits can be maintained. The use-case is already using valid-time for domain modelling, so it can't be repurposed to address the problem - possibly a good candidate for tri-temporality(?)

@Lisser might be able to add some extra details or a small example.

One workaround for this particular scenario might be to use another XT node as a secondary index (similarly to how the Lucene module works, without a separate tx-log / doc-store), but it is just an idea at this stage.

**Comment by xlfe** [comment]
+1 this would remove the need for some janky with-redefs we have for our tiered storage implementation!

**Comment by refset** [comment]
I expect the main design decision to resolve is how to handle transaction entries that don't respect the monotonic timestamp condition.

Options include:

1. Don't attempt to process the transaction, halt ingestion
2. Don't attempt to process the transaction, just skip it and log a warning
3. Process the transaction, but use the previous entry's timestamp instead, and log a warning
4. Process the transaction, but use the tx-log timestamp instead, and log a warning

For option (1) a fairly problematic scenario we probably want to avoid is accidentally making the tx-log (and system as a whole) ~unusable in the case that a misconfigured transaction producer inserts a timestamp far in the future, effectively blocking healthy processing thereafter. This could be mitigated by adding a means of skipping erroneous transactions during ingestion via node configuration.
