### ISSUE TITLE
Different behaviour between query and pull join cardinalities

### ISSUE THREAD

**Issue by malcolmsparks** [xtdb/xtdb#1544]
Consider these two cases:

```clojure
{:crux.db/id "https://example.org/template-models/fruits"
 :fruits ["apple" "orange" "banana"]}

{:crux.db/id "https://example.org/fruits.html"
 :template-model "https://example.org/template-models/fruits"}
```

And

```clojure
{:crux.db/id "https://example.org/template-models/fruits-a"
 :fruits ["apple" "orange" "banana"]}

{:crux.db/id "https://example.org/template-models/fruits-b"
 :fruits ["strawberry" "kiwi" "pineapple"]}

{:crux.db/id "https://example.org/fruits2.html"
 :template-model ["https://example.org/template-models/fruits-a"
                             "https://example.org/template-models/fruits-b"]}
```

Ordinarily, these entities can co-exist - the `:template-model` attribute can exist in both a singular and plural cardinality, which is beneficial because we don't yet have to choose!

Queries for `:template-model` will work the same way.

However, with `pull` syntax, we get different results.

For example:

```clojure
(crux.api/pull db
           '[{:template-model [*]}] "https://example.org/fruits.html")
```
 yields

```clojure
{:template-model
                  {:crux.db/id "https://example.org/template-models/fruits",
                   :fruits ["apple" "orange" "banana"]}}
```

whereas

```clojure
(crux.api/pull db
           '[{:template-model [*]}] "https://example.org/fruits2.html")
```

yields

```clojure
{:template-model
                  [{:crux.db/id "https://example.org/template-models/fruits-a",
                    :fruits ["apple" "orange" "banana"]}
                   {:crux.db/id "https://example.org/template-models/fruits-b",
                    :fruits ["strawberry" "kiwi" "pineapple"]}]}
```

Note the difference. My code that processes the pull result has to expect both singular and plural cases. The code that processes the query result only has to expect the plural case.

This is a subtle difference but means that I would avoid using pull entirely because it makes it harder to evolve cardinalities.

**Comment by refset** [comment]
Similar to the existing pull attribute parameter:
> :cardinality (reverse joins) - by default, reverse joins put their values in a collection - for many-to-one/one-to-one reverse joins, specify {:cardinality :one} to return a single value.

We _could_ add a `:many` option that instead takes effect on **forward joins**. (Further embracing the schema-on-read / schema-in-your-query ideals)

**Comment by jarohen** [comment]
As discussed, I don't think this is the right thing to be doing - `pull` returns documents from Crux, and takes its structure from what's in those documents. By putting a document into Crux with a scalar value, you're telling Crux that this is cardinality-one relationship - you could have put it in a singleton vector to say that it could potentially have multiple values.

We have the `:cardinality` option on reverse joins because there is no way, when there's only one document pointing back to a parent document, of Crux knowing whether that was supposed to be an actual cardinality-one relationship or a cardinality-many attribute that happens to only have one edge.

We can't be expected to offer flags to fix every schema mistake a user may make - this feels like a little ad-hoc bolt-on to fix one situation of many. The workaround here in user-space isn't overly taxing - let's opt for this over adding another flag that we then have to commit to maintaining.

**Comment by malcolmsparks** [comment]
Agreed.
