### ISSUE TITLE
Support Full Query Results

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#173]
A richer result is currently hidden in the meta of the result tuples. We should add a flag to the query map to optionally return these directly instead of the tuples. This flag could either be a boolean or an enum potentially.

This is useful when one wants to work directly with the documents, and can avoid having to pull out a lot of attributes one by one when one isn't actually filtering on them. This is already there in the meta data, but that's slightly obscure, and more importantly, doesn't work over HTTP, where you're likely to want this, as it can minimise chattiness.

**Comment by refset** [comment]
This is also important for establishing which document versions are relevant to a query so you can create correct CAS transactions.

**Comment by hraberg** [comment]
As discussed, let's add a test for this in `crux.api-test` and probably ensure that the internal records don't leak out and become proper edn.

**Comment by refset** [comment]
Reopening so we don't forget.

**Comment by jonpither** [comment]
So `full-results?` doesn't work over HTTP because of `BoundedResult` tuples returned, and it errors when the Edn containing them is sent over the wire (the client can't read back the Edn). Options are 1) deal with this at the `http-server` layer, just before the results are sent back over the wire - `crux.http-server/query`, or 2) we don't let the `BoundedResult` Defrecords escape the lower level query `crux.query/q` call.

I think for performance, it's not ideal to kill the `BoundedResult` coming out of the lower query level, and also, Defrecords are maps, so it feels a bit overcooking it to go the extra step to make them 'pure' maps and not defrecords. That said, you can't perform equals comparisons of defrecords and maps, so there is perhaps a bit more justification.

Will ponder the above.
