### ISSUE TITLE
Fix Unsafe Issue When Compiled on JDK8

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#183]
Compiling on JDK8 picks deprecated `int` overloads which are removed in JDK9 or later.
Issue is in `crux.ByteUtils/bufferToHex`, need to ensure all calls use the `long` overloads.

Might be worth adding `"-Xlint:-options,-path" "-Werror"` to `javac-options` to stop the build if there are warnings.

**Comment by jonpither** [comment]
I've released 19.04-1.0.2-alpha that is compiled using Java 10. Need to resolve the underlying issue as described in this post.

**Comment by jonpither** [comment]
Fixed by https://github.com/juxt/crux/commit/aeb2e6a73d6439ade2b0de41248e6a4d4b0dd674 - have tested building using Java8 and testing the bitemp tutorial using Java10. Going to leave this issue open a little longer so can consider what build steps and checks would've caught it. Can close this issue when subsequent issues are raised.
