### ISSUE TITLE
Nav links docs broken in Safari

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#198]

**Comment by refset** [comment]
![image](https://user-images.githubusercontent.com/456658/56773729-5a1c7000-67b7-11e9-9692-52fb8f19723b.png)

**Comment by refset** [comment]
The compiled function in question is `function J$(a){a=a.className;return ca(a)&&a.match(/\S+/g)||[]}` and I suspect it's probably related to one of these lines: https://github.com/juxt/website/blob/master/website/src-cljs/juxt/web/manual.cljs

**Comment by refset** [comment]
It might even be this: https://blog.cluster-text.com/2013/04/29/a-trap-when-looping-on-getelementsbyclassname/

**Comment by rlhk** [comment]
Same here. Works as expected in Chrome but not OSX Safari for me.

**Comment by refset** [comment]
It turns out that the null error is unrelated to the actual problem (though can be eliminated by removing the code which isn't needed). The real issue seems to be that Safari simply doesn't work properly when using `<details>` directly inside of a `<li>`, although you can still manually set `<details open>` even if you can't click to make that change happen. Arguably this is bug with Safari given that Chrome and Firefox don't have an issue. I am probably going to convert the `<ul>` tree to divs in the website code.

**Comment by refset** [comment]
This should be resolved now. We left the `<ul>` tree as-is and added some cljs to manually toggle the `open` property on the details tag to make Safari play along. Most importantly, we still keep the JS-free interactions for Chrome and Firefox.

**Comment by refset** [comment]
This is resolved sufficiently by the `<a>` linked titles workaround. The expand/collapse arrows still don't work as they should despite my best efforts trying to simulate the behaviour in cljs. Hopefully Safari will fix itself one day.
