### ISSUE TITLE
Ensure Transaction Spec Checks for Date not inst?

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#202]
We should avoid assuming Dates where we accept the `#inst` tag. This might be far reaching, but ultimately a fix is trivial.

Additionally it would useful to understand and document/avoid workflows that could lead to getting an `Instant` instead of a `Date`, as demonstrated in the screenshot below (@hraberg's guess is using Java 8 `java.time` "as default"):
![image](https://user-images.githubusercontent.com/456658/56901951-29775780-6a91-11e9-9ea8-2dcc63bfa97b.png)

cc @arrdem - thanks again for reporting

**Comment by hraberg** [comment]
I'm not going to speculate exactly what happened here as we have no full report, but it looks like an `java.time.Instant` has been used in the transactions (not the docs themselves) which is valid in our spec. This then hits the method above which assumes `java.util.Date` - wrongly, unless we change the `crux.tx` specs.

One solution, assuming this is the only issue here, is to remove the type hint in `crux.code/date->reverse-time-ms` and then use `inst-ms` instead of `.getTime` in the body.

We should do the above regardless, as the code is inconsistent with the spec it accepts, but would still be nice to know what actually caused it or at least manage to reproduce it.

**Comment by hraberg** [comment]
Reproducing should be possible by simply submitting a transaction with a valid-time that's an `Instant` and not a `Date`. The error will show in consumption, not on the submitting side.

**Comment by hraberg** [comment]
Initially I said we should just move to support `Instants` all over the place before looking closer to the issue, and there's no direct reason to do that in the context of this.

Actually, maybe the simplest fix is to change the spec itself to just assume `Date`s to avoid ambiguity here?

There's a bit of confusion in this entire space. `java.util.Calendar` (which isn't a `Date`) and `java.sql.Timestamp` (which is) both use the `#inst` reader tag, while `java.time.Instant` doesn't, while our API only accept `inst?` which for example isn't implemented for `Calendar`. That is, the EDN tag and the implementation aren't aligned as far as I can see.

For further context, but beyond this card, there are two other places where this matters:
1. The public Java API takes `Date` in many places, this could potentially be something more Java 8 friendly, but this isn't a bug.
2. The `crux.codec/ValueToBuffer` could have an implementation for `java.time.Instant` basically delegating to the `Date` implementation if we want to support range queries for them. Again, not a bug.

**Comment by hraberg** [comment]
Also, to be clear, if we decide to keep `inst?` we can't assume anything about the type (or it's ability to be represented as EDN) and can only use `inst-ms` on the other side. This is as `clojure.core/Inst` is a protocol which can be implemented by arbitrary types.

One of thing that makes this even more confusing is that we use Nippy on the wire by default, so things that isn't possible to express in vanilla EDN can be submitted without warning. Hence, narrower spec is to prefer and forcing `Date`.
