### ISSUE TITLE
Ability to build/deploy Maven artifacts

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#2179]
These went during the move from lein to deps.edn. It's still possible using tools.build, but would benefit from a helper script/`clojure -Tdeploy` or similar.

(Intentionally parked for the time being, see comments)

**Comment by wotbrew** [comment]
Just to summarise thoughts so far having spent a few hours setting up and looking around at whats out there.

Looking at current deploy tooling for deps projects, clojars seems to be the focus, deploying deps projects to central does not seem a well-trodden path - you struggle to find guides, tutorials or docs in general on how to do this.

Due to the fact the HTTP api of clojars is basically the same as central, it seems [deps-deploy](https://github.com/slipset/deps-deploy) could be used to deploy at least snapshots (I've tested with a dummy SNAPSHOT jar).

However the [requirements](https://central.sonatype.org/publish/requirements/) of central are different to clojars, and providing the necessary paperwork for releases may require some custom tools.build task.

- POM with a bit more detail than the default `clj -Spom` e.g licenses, perhaps scm and so on.
- javadoc & sources jars (can be empty if necessary)

I have asked on clojurians to see if anyone is aware of projects doing this, or any references or examples that might inspire other options.

As an aside, on reaction to seeing the lack of docs and guidance was considering _just_ creating a mvn project on demand and use the mvn cli to deploy. At least then the programmatic target is a simply a POM that we deploy using a widely used, documented tool.

**Comment by wotbrew** [comment]
Another consideration that was discussed with @jarohen was that the distribution audience for core2 jar's may be different to core1, and whether clojars (or even git sha deps) would be acceptable this time around. i.e as it stands we have clojure only client library.

**Comment by wotbrew** [comment]
Spent some time looking at reading ossrh credentials from `~/.m2/settings.xml`. It looked at a glance that aether via pomegranate via deps-deploy may 'just read them by default'. Unfortunately, it seems [not the case](https://wiki.eclipse.org/Aether/Creating_a_Repository_System_Session). So we'd have read the creds out (or invent some other credentials file or use envars) and pass them to aether. deps-deploy uses envars (CLOJARS_PASSWORD etc) _we could just do that_.

CAVEAT I may have just got something wrong, I'm not a mvn, pomegranate etc expert (never looked at them before!). This all seems way too involved compared to just using $build_tool that does this out of the box (e.g maven) with some kind of guide or example project. 

I've asked on Clojurians just in case these guides or examples (I'd be happy even with source code) exists - I'll come back to this if I get a good answer.
