### ISSUE TITLE
Limit and offset for pagination?

### ISSUE THREAD

**Issue by emil0r** [xtdb/xtdb#259]
From what I can see there is no support for pagination on the database level for really large result sets? Say I want to run a query that returns a million results. How do I paginate over that? For SQL I can limit the results returned by LIMIT and OFFSET typically, and so can query against a million results, but only have a 100 returned.

**Comment by hraberg** [comment]
Thanks @emil0r, the query engine supports`:limit` and `:offset` but seems this isn't documented. That said, `:offset` isn't efficient as it scrolls through the result set to the actual page each time. One workaround for that is to also use a range predicate like `>=` instead of `:offset` to skip stuff in a more efficient way, but that might not always be convenient or possible as it depends on the data.

Note: we should document all this.

**Comment by hraberg** [comment]
Will be documented as part of #177.
