### ISSUE TITLE
:crux.db/insert to let crux take care of generating id?

### ISSUE THREAD

**Issue by iku000888** [xtdb/xtdb#293]
I took a light stab at the crux api last night and I love it so far!
One thing that made mi tingle a bit though is  when ingesting documents we need to assign the :crux.db/id beforehand and there is a non zero chance of a collision if we are assigning random UUIDs.

I thought it would be convenient if there were an api that says "please assign this document an unused uuid" rather than putting the burden on the client, which I imagine would look like

```clojure
(crux/submit-tx
 system
 [[:crux.tx/insert
   {:name "Pablo" ;; No need to specify :crux.db/id
    :last-name "Picasso"}
   #inst "2018-05-18T09:20:27.966-00:00"]])
```

**Comment by refset** [comment]
Hi, glad to hear you approve :)

Whilst Crux _could_ potentially handle UUID generation I don't think we would want to attempt to tackle the problem of being 100% certain that UUIDs are unique within the core of Crux, although I think you have all the right primitives to try and achieve it on top of the core (via CAS). My guess would be that to fully address the possibility of UUID collision in the core would require drastically constraining the autonomy of nodes within a cluster, either in terms of throughput or latency, and therefore overall scalability.

Would a simple hash of the document itself be adequate as a `:crux.db/id` for your use-case?

**Comment by iku000888** [comment]
Thanks for getting back and clarifying the trade-offs!

Imagining the cas route, would one express something like...?

```
[:crux.tx/cas
 nil ;; cos it should not be there...?
 {:crux.db/id :the.new/thing}
  #inst "2018-05-18T09:21:31.846-00:00"]
```

And yes hash of the document should do :)

**Comment by refset** [comment]
Yep that's exactly right. `nil` in place of the document-map / document-hash makes sure nothing already exists.

One thing to bear in mind with the approach of using the hash of the document for your `:crux.db/id` is that you will need to keep referring to the _original_ hash of the document (since the subsequent versions will produce different hashes!), but hopefully that still makes sense for your needs. We will look at documenting this as a recommended pattern.

If that solves your immediate problem then feel free to close the issue when you're ready, although I'm happy to answer further questions. Thanks for raising the question!

**Comment by iku000888** [comment]
Thanks for all the clarifications!
