### ISSUE TITLE
Java API improvements

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#360]
Improvements to the general usage of the Java API can be made. As it stands, we are currently creating a new layer of Java API on top of the existing API, aiming to make it's usage strongly typed and immutable.

- [X] Create skeleton classes for operations, topologies and queries to get a feel for the general usage.
- [x] Add 'toEdn' functionality to necessary classes, generating data structures necessary to be passed down to underlying API. 
- [x] Allow strings to be used in queries.
- [x] Documenting usage of the wrapper API, with examples reflecting the clojure examples in the documentation.
- [x] Add information about topology classes to 'configuration' in the docs..
- [x] Create some basic Wrapper API tests

The above are currently suitable for releasing a vertical slice of the Java API. Further changes which can be made to the API:

- [ ] Wrap all functionality of underlying API.
- [ ] Test all contents of wrapper API.
- [ ] Change the topology generation to reflect the new style of topology classes.
- [ ] Fully typed queries
- [ ] Add javadocs for everything in the new API.
- [ ] Intersperse contents of quickstart doc with rest of docs

**Comment by kosiakk** [comment]
Documentation clearly demonstrates an intention to make Crux Java-friendly, which is awesome. Thank you for that!

Here are some of my impressions so far:
Current examples are mostly written in Clojure and they are somewhat easy to follow. But building your own examples/tests in Java, Scala, or Kotlin is quite tricky:
- Returned entity Map is immutable (it's not documented, it just fails at runtime). Using honest Clojure's IPeristentMap might be an option here?
- Normal lists and maps don't pass Spec validation with no explanation at all. At best I've got `vector?` message. My impression is that `submitTx` works only with Clojure types despite the signature.
- Snapshot argument is not ideomatic in Java, at all. I might accept `queryIterable` method, which returns a "box" object which implements both Closeable and Iterable. But even better would be to return just Iterable and rely on finalization queue to close the snapshot. Is it really that expensive to keep snapshot open a bit longer than needed?
- There must be some quick-start in Java or Kotlin. You'll get all the love of Clojure community anyway, but for a simple Java devs it might look quite alien. Let's maybe use a bit of ~~Latin~~ Java to be understood by the majority of developers of the JVM ecosystem.

I'm sure you are on the right path to success :)

**Comment by danmason** [comment]
We're definitely on the same train of thought, here!

To address some of your points:
- As it stands some of the type signatures are somewhat inaccurate and need going through and clarifying. We are looking at a couple of different options when it comes to this.
- You are correct, as it currently stands, submitTx only works with Clojure types. We're currently working on updating the API somewhat to make it more Java-idiomatic, hopefully removing the need for some of the Clojure specific implementation detail. Additionally, going to be looking further at the behavior of the spec. 
- After the API changes have been made, I plan to add proper java examples to different areas of the documentation, such that it will be more friendly to approach in the future.

**Comment by jarohen** [comment]
from discussion this morning:

* splitting this up into a few distinct changes - fixing the spec bug in #372, @danmason's working on the Java API for topologies, and then a wider discussion required about the transaction/query Java/Kotlin API

Regarding the wider Java/Kotlin API discussion, a start at some properties we'd like of an ideal solution:

* Ideally non-Clojure devs won't need to concern themselves with Clojure implementation details - e.g. `Keyword.intern`, Clojure collection types, etc
* Have (the option of) compile-time checks that prevent as many invalid requests as possible
* Have the API set up such that IDEs can help auto-complete as much as possible
* Strong typing - no 'Object's unless required
* Not _too_ verbose (although it is Java :wink: )

Learning from Clojure, we'd also like the following properties, although not at the expense of making the API hard to understand or use:
* Declarative over imperative
* Immutable over mutable

The 'strong typing' property, in particular, conflicts with what Clojure tends to manipulate - if we're to go in this direction, we'll need to consider whether/where we'd want to convert between strongly typed and weakly typed worlds (or maybe we can think of a way to make the strongly typed objects behave like Clojure's data structures?)

Currently, Crux's clojure core frequently calls in via the external Java API - the benefit being that the Java API is exercised and we can ensure it doesn't go stale. The tradeoff of this, though, is that the Java API needs to accept Clojure data structures. If we wanted the Java API to be 'more strongly typed', we'd need to consider these internal calls. One possible solution would be to invert what we have currently - rather than having the Clojure implementation call the Java API, we might have a completely Clojure core, with the Java API being an adapter layer around the edge, performing any required transformations. Users' Clojure code would get an instance of `PCruxNode` (rather than `ICruxAPI`), which it would call with Clojure data structures; users' Java code would call `ICruxAPI` with Java data structures; the implementation would then transform these and pass them to an instance of `PCruxNode`.

Food for thought!

**Comment by danmason** [comment]
Have rewritten the card somewhat to reflect the current state/ideas of the API changes.
