### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by Tails** [xtdb/xtdb#361]
Crux looks great, but is it possible to hook it into GraphQL to expose it as a service? (Like Irmin/DGraph)

**Comment by kosiakk** [comment]
I'd love to have it! But there are tricky details:
- Schema plays a very central role in the whole GraphQL story, but Crux doesn't really have a schema. Attributes are not defined in advance, and I'm not even talking about classes. 
- Datalog query language is more powerful than GraphQL, by design. Take a look at DGraph - they have GraphQL± as _the only_ interface for querying, but it's quite far from the standard. Mutations are done in RDF shape. 

At very least, some kind of schema would be required in such crux-graphl module, which will introduce classes, distinguish reference-attributes from value-attributes, provide documentation, and deal with backwards-compatibility

**Comment by Tails** [comment]
You are right, DGraph also commented on their GraphQL journey [in a blog post recently](https://blog.dgraph.io/post/building-native-graphql-database-dgraph/) making similar points. GraphQL is effectively constraining the possibilities of the database.
