### ISSUE TITLE
An eviction can clobber documents referenced outside its valid-time range

### ISSUE THREAD

**Issue by psagers** [xtdb/xtdb#375]
A demonstration:

```clojure
;; Insert a document at three valid-times, but with only two distinct values.
dev=> (crux/submit-tx node [[:crux.tx/put {:crux.db/id :doc-a, :value 0} #inst "2019-01-01"] 
                            [:crux.tx/put {:crux.db/id :doc-a, :value 1} #inst "2019-01-02"] 
                            [:crux.tx/put {:crux.db/id :doc-a, :value 0} #inst "2019-01-03"]])
#:crux.tx{:tx-id 3, :tx-time #inst "2019-11-02T16:42:26.752-00:00"}

;; Retrieve the current value.
dev=> (crux/entity (crux/db node) :doc-a)
{:crux.db/id :doc-a, :value 0}

;; Evict the document at the first two valid-times. This should not impact the most recent value.
dev=> (crux/submit-tx node [[:crux.tx/evict :doc-a #inst "2019-01-01" #inst "2019-01-02T00:00:01" false false]])
#:crux.tx{:tx-id 4, :tx-time #inst "2019-11-02T16:43:53.688-00:00"}

;; Try to retrieve the current value again.
dev=> (crux/entity (crux/db node) :doc-a)
nil
```

For further confirmation, you can inspect your document log. The eviction overwrote both document values, despite the fact that one of them (`{... :value 0}`) was still referenced outside of the eviction range.

Does `:crux.tx/evict` need to walk the entire entity history and do some set algebra to decide which documents are still referenced? Do document log entries need to be refcounted somehow? Something less scary?

**Comment by refset** [comment]
Hi there! Each document version has a unique `content-hash` generated based on the contents, so identical document versions will be deduplicated internally because they share the same hash. This means all references to a given version are implicitly connected. The eviction behaviour is therefore operating as expected, though we should definitely clarify this in the docs.

If you think the API should provide an option to behave as you initially expected I would be keen to hear more about the use-case.

Hope that helps!

**Comment by psagers** [comment]
I agree that the code appears to be doing what it's meant to; this is mostly about a sharp edge to the API that seems destined to cause data loss in odd cases. Most likely a low-incidence but high-consequence risk.

To take one example, say I have a document that accumulates personal information over time. At some point, I no longer want all of the details but I still want statistics, so I replace it with a final pre-aggregated value and evict all but the last version. Except that through some quirk of application logic (maybe a bug, maybe just an edge case), the same final value gets put twice. Or it was a trivial case where the aggregation was a no-op (maybe a re-aggregation). Either way, the eviction now destroys it all, a punishment perhaps disproportionate to the crime.

This may be solvable to a large extent at the documentation level by making it clear that eviction is a low-level operation that will destroy more data than you expect if you don't understand the precise semantics. As it stands, the arguments to `:crux.tx/evict` are really more a low-level query than a set of constraints, which is a pretty subtle distinction.

One workaround at the application level will be to add, say, `{:eviction-guard <new-uuid>}` to every new document version if you're assuming uniqueness but can't otherwise prove it. Which still means thinking carefully about when and why you might be required to manage uniqueness. And it would have to be done at a lower level than any potential double-put anomaly. Depending on the application requirements, one might also be able to only ever evict entire document histories, copying any data you want to rescue onto a new document ID.

One potentially simple API improvement might be to allow the caller to provide one or more document hashes that are to be exempted no matter what. That would map nicely onto at least one reasonable scenario in which you put a new value and then evict everything that's not that.

There seems bound to be some tradeoff between cognitive load and implementation complexity here and I think either direction is defensible. I would agree though, that this is an area for aggressive documentation.

**Comment by psagers** [comment]
Here's a subtler variation on the theme:

```clojure
dev=> (crux/submit-tx node [[:crux.tx/put {:crux.db/id :doc-a, :value 0}]])
#:crux.tx{:tx-id 2, :tx-time #inst "2019-11-02T20:27:56.774-00:00"}

dev=> (crux/entity (crux/db node) :doc-a)
{:crux.db/id :doc-a, :value 0}

;; This evict undermines the subsequent put.
dev=> (crux/submit-tx node [[:crux.tx/evict :doc-a]
                            [:crux.tx/put {:crux.db/id :doc-a, :value 0}]])
#:crux.tx{:tx-id 3, :tx-time #inst "2019-11-02T20:29:02.094-00:00"}

dev=> (crux/entity (crux/db node) :doc-a)
nil
```

**Comment by hraberg** [comment]
So as seen in #428 we're removing ranges from evict for now, so this problem indirectly goes away once that work has been done. As mentioned there, we might revisit.

**Comment by hraberg** [comment]
Split out from #428.

There is a race condition which would happen if someone tries to resurrect a document in quick succession of evicting it. We also need to mitigate someone submitting a new document for an evicted entity.

Record evicted entity ids, these would simply be key-values stored by the evict op in a new internal index.
If a document arrives for an entity which has been marked as evicted, drop it instead of indexing and storing it, and emit a new tombstone to get rid of it again on Kafka. Log at debug or warn.
On the transaction side, potentially blow up the transaction in a general pre-condition if an operation involves an evicted event, alternatively log a warning and do nothing.
One could potentially introduce a new operation :crux.tx/unevict to allow writes to the entity id again at a later stage, but think that would be a separate card and discussion for sure. Can easily imagine opening up for various new race conditions.

**Comment by jarohen** [comment]
will close this one for the time being given that #428 is now released - but yes, absolutely something for us to bear in mind when the functionality returns

**Comment by refset** [comment]
Thanks again @psagers for raising the issue and for all your thoughts & suggestions - it will undoubtedly help us determine a satisfactory compromise when we revisit this area in the near future.
