### ISSUE TITLE
Bitemp Test Intermittent Failure in CI

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#421]
This is failing often enough to warrant it's own card:

```
FAIL in (test-bitemp-query-from-indexing-temporal-data-using-existing-b+-trees-paper) (query_test.clj:1549)
expected: (= #{[:p4 :NY #inst "2019-01-02T00:00:00.000-00:00" :na] [:p3 :LA #inst "2018-12-31T00:00:00.000-00:00" :na] [:p2 :SFO #inst "2018-12-31T00:00:00.000-00:00" :na]} (api/q (api/db *api* #inst "2019-01-02T00:00:00.000-00:00" (:crux.tx/tx-time third-day-submitted-tx)) (quote {:find [p entry-pt arrival-time departure-time], :where [[p :entry-pt entry-pt] [p :arrival-time arrival-time] [p :departure-time departure-time]]})))
  actual: (not (= #{[:p4 :NY #inst "2019-01-02T00:00:00.000-00:00" :na] [:p3 :LA #inst "2018-12-31T00:00:00.000-00:00" :na] [:p2 :SFO #inst "2018-12-31T00:00:00.000-00:00" :na]} #{[:p1 :NY #inst "2018-12-31T00:00:00.000-00:00" :na] [:p4 :NY #inst "2019-01-02T00:00:00.000-00:00" :na] [:p3 :LA #inst "2018-12-31T00:00:00.000-00:00" :na] [:p2 :SFO #inst "2018-12-31T00:00:00.000-00:00" :na]}))
```

Likely related to #321 and might be caused by Moberg. But there's also a "TODO: Remove this sleep" at the start of the test, so might be worth sanity checking.

**Comment by hraberg** [comment]
One idea that has been floated on the other moberg related cards is to run the `crux.query` tests against JDBC with H2 for a while as fixture instead and see if these intermittent tests disappear. If they don't the issues might be in the shared polling code or somewhere else.

**Comment by jarohen** [comment]
think I got it - it's to do with Moberg's log compaction.

there's two instances of the same document being ingested, at two different valid times; those documents get put onto Moberg's tx-topic twice. the second time it gets put on the topic, it removes the first one, because compaction (the same way Kafka does)

but, in Moberg (unlike Kafka), it doesn't wait for all the docs to be in the object store before it runs the transaction - reckon it assumes the documents will always be indexed first, or something, so the tx's document isn't in the object store when the transaction runs, the transaction fails, and the indexer continues

the effect of the sleep is that the first transaction runs before the second instance of the document gets ingested, so the compaction only happens after the transaction's already been indexed
