### ISSUE TITLE
Question: Would it be possible to store a piece of code that was used to create a transaction?

### ISSUE THREAD

**Issue by felippemr** [xtdb/xtdb#426]
Thanks for such an awesome project. This is heaven for financial application developers that need to have an immutable and preserved history while giving users the ability to create transactions in the past.

Having that said, financial software is usually created around laws or regulations that may change. However, I would like to be able to understand the state of the app and the code used to create/update/delete something at a certain point of time. 

Would it be possible to be done with crux?

**Comment by t-taylor** [comment]
Hi felippemr. Thanks for the feedback, we're glad you're enjoying crux! I'd
recommend doing this using a wrapper function for submit-tx rather than writing
some lower-level implementation. One of the ideals of crux is keeping the core
light, so making submit-tx do anything else other than submit transactions is
probably a bad idea as it adds a hidden side effect somewhere in the internals.
However by writing a wrapper which adds something like a log document could
indeed be possible. One of the nice things about using a data structure as a
query in datalog in clojure is you can do all the things you can normally with
a hashmap.
For example, you could write a wrapper for submit-tx which appends logging info
to all `:crux.tx/put` transactions:

```
(defn tx-put
    [doc function]
    (let [logging {:crux.db/id (java.util.UUID/randomUUID)
                   :log/document doc
                   :log/time (tick/now)
                   :log/namespace *ns*
                   :log/machine (sys/ident)
                   :log/source (git/hash)
                   :log/anything-you-want-really (func/tion)
                   :log/function function}]
     [[:crux.tx/put doc][:crux.tx/put logging]]))
(defn submit-tx
    [txs]
    (crux.api/submit-tx
        (apply concat (map #(case (first %) :crux.tx/put (tx-put %)) txs)))
```

And to see all logging info from a doc `d` with `:value` `v`:
```
(crux.api/q db {:find ['log]
                :where [['d :value v]
                        ['log :log/document 'd]]
                :full-results? true})
```

This would also have the added benefit that using db snapshot also shows to the
state of the code through logging as well as the data.

I hope this helps!

**Comment by felippemr** [comment]
I will try it out, thanks!
