### ISSUE TITLE
Optimising the Crux disk-space requirements

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#465]
Potential solutions:
* Allowing users to save disk space by compacting older data (accepting that it will no longer be accessible by temporal queries)
* Splitting out storage, keeping current storage local to the node, historical storage shared between nodes on a higher-latency store (NFS, say)

## Chat 2020-05-12

Let's have another round of iteration on this. 

* (#754) Had a pass at removing the C from the AEVC and AVEC indices. Saved ~60-70% disk space on certain benchmarks but it ran slow on watdiv queries, seemingly because the query engine had to go to the object store to resolve each of the values in the tuples
* (#821) Adding a separate CAV index, so that the query engine doesn't go to the object store. Didn't save as much disk space (~35-40%) as removing C, and ingest was slower, but queries were much more acceptable.
* Next round - let's try re-jigging the indices, changing the denormalisation we perform to balance disk space, ingest speed and query speed.

**Comment by hraberg** [comment]
A couple of other approaches:
* Sanity check storage using different compaction flags for Rocks.
* Replace hashes in the index with numeric ids. This requires a mapping step and indexes that tracks hashes to and from their numeric ids. If one wants to really optimise for space one can go for ints (configurable). Various schemes to compress the integers to variable length would complicate the query engine a lot. This extra mapping needs a large in-memory cache. One need to test to see the performance impact, which might even be positive due to the smaller data on disk, but my guess is that tracking and checking for ids would slow things down.
* Mapping the attributes to their own id space, similar to above, but they could likely be ints or even shorts (configurable).

**Comment by hraberg** [comment]
Some statistics after ingesting watdiv.10M.nt, Rocks is 1.1G on disk:

```
| :id | :entries | :key-size | :value-size | :total-size |                                     :name | :size-percent |       :size-entry |
|-----+----------+-----------+-------------+-------------+-------------------------------------------+---------------+-------------------|
|   1 | 11438042 | 968276200 |           0 |   968276200 |                             avec-index-id |            36 | 84.65401683260124 |
|   2 | 11438042 | 968276200 |           0 |   968276200 |                             aecv-index-id |            36 | 84.65401683260124 |
|   0 |   521585 |  11474870 |   617033332 |   628508202 |                content-hash->doc-index-id |            23 | 1204.996696607456 |
|   3 |   521585 |  23992910 |    10953285 |    34946195 | entity+vt+tt+tx-id->content-hash-index-id |             1 |              67.0 |
|   7 |   521585 |  23992910 |    10953285 |    34946195 |     entity+z+tx-id->content-hash-index-id |             1 |              67.0 |
|   4 |        3 |        66 |        3404 |        3470 |                  meta-key->value-index-id |             0 | 1156.666666666667 |
|   5 |        1 |         1 |           8 |           9 |                     failed-tx-id-index-id |             0 |               9.0 |
|   5 |        1 |         1 |           8 |           9 |                    index-version-index-id |             0 |               9.0 |
```

**Comment by jarohen** [comment]
Happy to call this done for now, after the 1.9 release :smile:
