### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#6]
Ability to take a backup of the KV store and restore it on another node.

A variant can be to seed it on start with a URL to either a directory or S3 resource to bootstrap the KV store from.
There should also be a way to trigger the backup of a running node.

We're currently want to avoid building intelligence about when to do these actions into the code itself as long as it can be scripted.

**Comment by hraberg** [comment]
One idea is to use Zookeeper to find another existing node, and asking it to send a snapshot of its index.

**Comment by hraberg** [comment]
I think we're currently looking at ability to take a node offline and back it up and restore it that way, entirely using normal bash scripts. While we have features for backing up the internal KV store already, that will require more work to expose and make scriptable against a running instance, for example via an admin API over (local?) HTTP or similar.

**Comment by hraberg** [comment]
We kind of want this, but this is dependent on actual realistic setups and usage. As mentioned above, the low-level details for this are provided both internally by the the `KvStore` protocol, and Crux can by design be shutdown and its data copied to another node, so it's possible to script this in various ways.

Moving to post phase 2 until something more concrete happens here.

**Comment by hraberg** [comment]
It's somewhat dependent on other ops cards, like  xtdb/xtdb#99 and xtdb/xtdb#1992.

**Comment by megakorre** [comment]
If we want a backup/restore version that can be run while the instance is still running we can 
mimic how elasticsearch does it.

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

They refer to it as "Snapshot and Restore" which is maybe a more descriptive name for us too.
Since the backup (atleast in the Kafka mode) is more of a performance feature rather than a 
disaster recovery feature.
