### ISSUE TITLE
args w/ predicate query stopped working after 1.6.2

### ISSUE THREAD

**Issue by akacase** [xtdb/xtdb#732]
This might be my fault, but it seems like a regression to me:

```clojure
(defn union-thing
  "passes a vector of keys to look for in the `anchors`"
  [v]
  (q
   {:find '[e]
    :where '[[e :key k]
              [e :crux.db/id e]
              [e :anchors a]
              [(not (nil? (get g a)))]]]
    :args (vec (for [k v]
                 {'g k}))}))
```

**Comment by refset** [comment]
Hi @akacase - I haven't tried to reproduce this so far, but it doesn't look it should have worked correctly previously in any case. The problem is that the `[(not (nil? (get g a)))]` clause is not valid Crux Datalog, because you cannot nest a Clojure predicate like `nil?` and a Clojure function like `get` as shown, inside of a Datalog `not`.

You have two options:

1. create a Clojure function and reference it as a predicate using a fully qualified name (i.e. with the namespace).

```clojure
(ns myns)
(defn not-nil-get [g a]
  (not (nil? (get g a))))

(defn union-thing
  "passes a vector of keys to look for in the `anchors`"
  [v]
  (q
   {:find '[e]
    :where '[[e :key k]
              [e :crux.db/id e]
              [e :anchors a]
              [(myns/not-nil-get g a)]]]
    :args (vec (for [k v]
                 {'g k}))}))
```

OR

2. Use intermediate vars (note that clojure.core predicates are built-in, but otherwise it would be fully qualified too, like `[(clojure.core/get g a) b]` etc.)

```clojure
(defn union-thing
  "passes a vector of keys to look for in the `anchors`"
  [v]
  (q
   {:find '[e]
    :where '[[e :key k]
              [e :crux.db/id e]
              [e :anchors a]
              [(get g a) b]
              (not [(nil? b)])]
    :args (vec (for [k v]
                 {'g k}))}))
```

I haven't benchmarked this, but ideally the Datalog approach would not be significantly slower, especially in relation to larger datasets & queries.

I hope that makes sense & I would be interest to know which one you opt for!

**Comment by akacase** [comment]
went with the first suggestion, easier to debug!! Thanks for the prompt response and stay healthy!
