### ISSUE TITLE
Aggregations in the query engine

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#809]

**Comment by jorinvo** [comment]
Interesting! Will this provide similar functionality like the [aggregation decorator](https://github.com/crux-labs/crux-decorators)?
Was looking into how to best integrate the aggregator decorator into the HTTP server since our use case is via HTTP and for obvious performance reasons aggregations must happen on the database side. Would this provide an alternative here?

**Comment by jarohen** [comment]
Hey :) yes, it'd be similar - although we're considering including this as part of the query engine so that it can be more performant.

**Comment by jorinvo** [comment]
Thanks for the update :slightly_smiling_face:  That sounds awesome! Looking forward to finding out more :) In this case I won't bother looking into the decorator and wait instead.

**Comment by jarohen** [comment]
Hopefully it will be, yes :) just to manage expectations, though, this is currently a fair way down our backlog, could be a while til it lands in core (particularly as it likely involves pretty significant work in the query engine).

**Comment by iku000888** [comment]
Is this feature different from aggregates in datomic? https://docs.datomic.com/on-prem/query.html#aggregates
