### ISSUE TITLE
Vector IDs

### ISSUE THREAD

**Issue by theronic** [xtdb/xtdb#892]
Why are maps supported as IDs, but not vectors?

E.g. `#crux/id {:this :id-field}` but not `#crux/id [:this :id-field]`?

I would like to be able to store an integer ID from an external service, e.g. `#crux/id [:external/service 12345...]`.

**Comment by jarohen** [comment]
Hi @theronic - this should be possible using `{:external/service 12345}`?

**Comment by theronic** [comment]
Sure, I realize that, but why aren't vectors allowed as IDs? Is it related to hashing?

**Comment by jarohen** [comment]
Ah, I see - it's because vectors (and sets) are used for cardinality-many values in Crux - `{:crux.db/id :foo, :values [:bar :baz]}` will be returned for both `'{:find [?e] :where [[?e :values :bar]]}` and `'{:find [?e] :where [[?e :values :baz]]}`. We decompose these values in the indices, rather than storing them as vectors, which means we can't join against the original vector, if it were to be an entity ID.

HTH? :) 

James
