### ISSUE TITLE
Use pred-fn to bind a leaf var

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#907]
We currently use multiple `:where` clauses to project out multiple values from a document. Using multiple clauses means that we need to ensure that any document in the results must have all of the attributes, and therefore this entity takes part in the join algorithm (potentially many times, especially in SQL relations, see #514). 

(see #904 for an complementary approach to make these joins faster)

In practice, though, the user will often only need to explicitly filter based on one attribute, and then they'll know that the others are present - for example, if we know that any user document always has a name and an email, we only need to find the document itself, and then we can project out the other fields.

Let's add a `get` function to the query engine that will optionally bind a var, as follows:

```clojure
{:find [?u ?name ?email]
 :where [[?u :user/id]
         [(get ?u :user/name) ?name]
         [(get ?u :user/email) ?email]]}
```

(see also: pull syntax, #849)

**Comment by jonpither** [comment]
Part of this task (which could moved to a separate issue) is to expose db and index-store to datalog fns. The `get` function will need this access.

**Comment by jonpither** [comment]
We had also discussed naming this `optional` - final naming to be finalised.

**Comment by jonpither** [comment]
I have spiked an approach for this that does yield some query-time performance. 

Using the TPCH dataset querying 300k line-items and 10 projected 'leaf var' fields, I reduced a `select *` query time down from ~55 secs to ~35 by introducing a hardcoded pred fn.

Old query:

```
  {:find [l_orderkey],
   :where [[e :l_orderkey l_orderkey]
           [e :l_partkey l_partkey]
           [e :l_suppkey l_suppkey]
           [e :l_linenumber l_linenumber]
           [e :l_quantity l_quantity]
           [e :l_extendedprice l_extendedprice]
           [e :l_discount l_discount]
           [e :l_tax l_tax]
           [e :l_returnflag l_returnflag]
           [e :l_linestatus l_linestatus]
           [e :l_shipdate l_shipdate]
           [e :l_commitdate l_commitdate]]
   :timeout 100000}
```

New query:

```
{:find [l_orderkey],
   :where [[e :l_orderkey l_orderkey]
           [(crux.query/optional e :l_partkey) l_partkey]
           [(crux.query/optional e :l_suppkey) l_suppkey]
           [(crux.query/optional e :l_linenumber) l_linenumber]
           [(crux.query/optional e :l_quantity) l_quantity40]
           [(crux.query/optional e :l_extendedprice) l_extendedprice]
           [(crux.query/optional e :l_discount) l_discount]
           [(crux.query/optional e :l_tax) l_tax]
           [(crux.query/optional e :l_returnflag) l_returnflag]
           [(crux.query/optional e :l_linestatus) l_linestatus]
           [(crux.query/optional e :l_shipdate) l_shipdate]
           [(crux.query/optional e :l_commitdate) l_commitdate]]
   :timeout 100000}
```

 I went with a hardcoded pred called `optional` to do an `aev` call on the index-store. The hardcoded pred is faster than a normal pred fn, because:

* no need to decode the vars
* no need to encode the pred-results
* no need for `apply` usage

See: https://github.com/jonpither/crux/commit/37b97215b5e27f67422404a80358e2cbf7559174#diff-883be45d5393e64c09b3b5aee6c26a58R546

In this spike I also hacked `update-relation-virtual-index2!` to skip an encoding step.

This pred is going to be called for each field, for each result, so (300K * 10). I think there are possible further gains by optimising the planner as to have a single pred-fn for all 10 fields in one go, and thus using a single `seek` in the process.

Where to go from here?

There are two options - if we want to grab this perf improvement, we could rewrite incoming queries as to use this hardcoded pred-fn for leaf vars. The other option is to do a deeper change and rework in the indexes so that a bunch of leaf-vars will end up in the same index - this is commented on in https://github.com/juxt/crux/issues/905.

My preference is for the latter, but that's a harder change.
