### ISSUE TITLE
crux.api/entity "cold read" broken since 1.9.0

### ISSUE THREAD

**Issue by bennyandresen** [xtdb/xtdb#957]
hey everyone,

sorry for the weird title. I don't know how else to summarize the following:

### Prerequisite
Previously generated document has been `put` into the persistent database. (I've only tested lmdb and rocksdb.)
`[[:crux.tx/put {:crux.db/id :ivan, :age 42}]]`

### Steps to reproduce
Start up the node using the same topology as what was used to submit the transaction from the previous step.
```
(defn start-node [storage-dir]
  (crux/start-node {:crux.node/topology '[crux.standalone/topology
                                          crux.kv.rocksdb/kv-store]
                    :crux.kv/db-dir (str (io/file storage-dir "db"))}))
```

#### Actual result (broken on 20.06-1.9.1-beta)
deps.edn:
```
{:deps {juxt/crux-core {:mvn/version "20.06-1.9.1-beta"}
        juxt/crux-rocksdb {:mvn/version "20.06-1.9.1-beta"}}}
```
```
(def crux (start-node "./resources/"))
(crux/entity (crux/db crux) :ivan) ;; => nil
```

#### Expected result (works on 20.06-1.8.5-alpha)
deps.edn:
```
{:deps {juxt/crux-core {:mvn/version "20.06-1.8.5-alpha"}
        juxt/crux-rocksdb {:mvn/version "20.06-1.8.5-alpha"}}}
```
```
(def crux (start-node "./resources/"))
(crux/entity (crux/db crux) :ivan) ;; => {:crux.db/id :ivan, :age 42}
```

Am I doing something wrong or is this a regression?

**Comment by jarohen** [comment]
Morning @bennyandresen, thanks for the report :) will take a look

**Comment by jarohen** [comment]
At first glance it looks like this is a result of #818 (although that did affect 1.8.5 as well) - could you try adding the following to your topology config?

```clojure
:crux.standalone/event-log-kv-store 'crux.kv.rocksdb/kv
:crux.standalone/event-log-dir (str (io/file storage-dir "event-log"))
```

Unfortunately what's happening here is that, when using the standalone transaction log/document store, without the above config it defaults to being in-memory, but the query indices are being saved to disk (because of the `:crux.kv/db-dir`). When the node restarts, the (supposedly 'golden store'!) transaction log/document store are empty, which causes all kinds of confusion in the query engine - quite a sizeable gotcha that we either need to make easier or document thoroughly.

What I did to repro the issue:
* Using https://github.com/juxt/crux/blob/master/dev/user.clj as a base, remove the `:crux.standalone/*` config from the node config, clear storage directories, start JVM + node, `(user/go)`
* Submit `:ivan` doc
* Check `(crux/entity ...)`, fine
* Restart the node, `(user/halt)`, `(user/go)`
* Check `(crux/entity ...)`, nil.

Works with the same steps but re-adding the `:crux.standalone/*` config.

Could you check it with the above config and let me know if it fixes your issue? Cheers!

**Comment by bennyandresen** [comment]
@jarohen Thanks for looking at this so quickly!
The topology configuration above did solve my "cold start" issue.

To maybe illuminate my lack of the event-log configuration is that I followed (a few weeks ago) the Crux tutorial and just added RocksDB to it: https://juxt.pro/blog/posts/crux-tutorial-setup.html#_power_up

And it worked fine and persisted between invocations. Only now with the (very exciting) 1.9 release did I find this behavior changed.

**Comment by jarohen** [comment]
> To maybe illuminate my lack of the event-log configuration is that I followed (a few weeks ago) the Crux tutorial and just added RocksDB to it: https://juxt.pro/blog/posts/crux-tutorial-setup.html#_power_up

Aha, thanks - will get that updated
